version: '3.7'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOSTNAME=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - DATABASE=inventaris-ci
    expose:
      - "9090"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: inventaris-ci
    volumes:
      - mysql-data:/var/lib/mysql
      - ./inventaris_skripsi.sql:/docker-entrypoint-initdb.d/inventaris_skripsi.sql
    ports:
      - "3302:3306"

volumes:
  mysql-data:
